main:
  download_repository: "https://github.com/Dyrutter/anime_recommendations#download"  
  project_name: anime_recommendations
  experiment_name: development
  execute_steps:
    - download
    - preprocess
    - neural_network
    - similar_anime
    - similar_users
    - recommendation
    - API
  random_seed: 42

data:
  stats_url: "https://github.com/Dyrutter/anime_recommendations/blob/main/data/user_stats.parquet?raw=True"
  synopses_url: "https://github.com/Dyrutter/anime_recommendations/blob/main/data/synopses.csv?raw=True"
  all_anime_url: "https://github.com/Dyrutter/anime_recommendations/blob/main/data/all_anime.csv?raw=True"

  stats_artifact: "user_stats.parquet"
  stats_artifact_type: "raw_data"
  stats_artifact_description: "Main statistics file. Contains columns 'user_id', 'anime_id', 'watched_episodes', 'rating', 'watching_status'"
  stats_artifact_latest: "user_stats.parquet:latest"

  synopses_artifact: "synopses.csv"
  synopses_artifact_type: "raw_data"
  synopses_artifact_description: "File containing synopses"
  synopses_artifact_latest: "synopses.csv:latest"

  all_anime_artifact: "all_anime.csv"
  all_anime_type: "raw_data"
  all_anime_description: "File containing descriptive stats for all anime"
  all_anime_artifact_latest: "all_anime.csv:latest"

  preprocessed_stats: "preprocessed_stats.parquet"
  preprocessed_artifact_type: "preprocessed_data"
  preprocessed_artifact_description: "Preprocessed stats file to be used for model training"
  preprocessed_artifact_latest: "preprocessed_stats.parquet:latest"

  num_reviews: 50
  drop_half_watched: True

  save_raw_locally: False
  save_clean_locally: True

model:
  test_size: 0.3
  kernel_initializer: 'he_normal'
  TPU_INIT: False
  start_lr: 0.00001
  min_lr: 0.00001
  max_lr: 0.00005
  batch_size: 10000
  rampup_epochs: 5
  sustain_epochs: 0
  exp_decay: 0.8
  embedding_size: 128
  model_loss: 'binary_crossentropy'
  optimizer: 'Adam'
  weights_artifact: 'wandb_anime_weights.h5'
  epochs: 20
  activation_function: 'sigmoid'
  checkpoint_metric: 'val_loss'
  save_weights_only: True
  save_best_weights: True
  save_freq: 'epoch'
  save_model: True
  model_name: './wandb_anime_nn.h5' # Path to use if you want to save model to your local machine
  verbose: 1
  model_artifact: 'wandb_anime_nn.h5'
  history_csv: 'wandb_anime_nn_history.csv'
  monitor: 'val_loss'
  mode: 'min'
