main:
  download_repository: "https://github.com/Dyrutter/anime_recommendations#download"  
  project_name: anime_recommendations
  experiment_name: development
  execute_steps:
    - download
    - preprocess
    - neural_network
    - similar_anime
    - similar_users
    - user_prefs
    - user_recs
    - model_recs
    # - API
  random_seed: 42
  interval: 3000 # Time in milliseconds to display any figures on local machine

data: # Data artifacts
  stats_url: "https://github.com/Dyrutter/anime_recommendations/blob/main/data/user_stats.parquet?raw=True"
  synopses_url: "https://github.com/Dyrutter/anime_recommendations/blob/main/data/synopses.csv?raw=True"
  all_anime_url: "https://github.com/Dyrutter/anime_recommendations/blob/main/data/all_anime.csv?raw=True"

  stats_artifact: "full_data_set.parquet" # Raw version of main data frame
  stats_artifact_type: "raw_data" # Type of raw version of main data frame
  stats_artifact_description: "Main raw statistics file." # Description of raw version of main data frame
  stats_artifact_latest: "full_data_set.parquet:v0" # Used artifact version of main data frame

  synopses_artifact: "synopses.csv"
  synopses_artifact_type: "raw_data"
  synopses_artifact_description: "File containing synopses"
  sypnopses_artifact_latest: "synopses.csv:latest"

  all_anime_artifact: "all_anime.csv"
  all_anime_type: "raw_data"
  all_anime_description: "File containing descriptive stats for all anime"
  all_anime_artifact_latest: "all_anime.csv:latest"

  preprocessed_stats: "preprocessed_stats.parquet"
  preprocessed_artifact_type: "preprocessed_data"
  preprocessed_artifact_description: "Preprocessed stats file to be used for model training"
  preprocessed_artifact_latest: "preprocessed_stats.parquet:v2" # Currently with <400 reviews removed

  num_reviews: 400 # Minimum number of reviews a user must have made in order to be considered
  drop_half_watched: False # Drop instances where a user has watched less than half the episodes
  drop_unwatched: False # Drop instnaces where a user hasn't watched any episodes
  drop_plan: False # Drop instances where a user only plans to watch the anime

  save_raw_locally: False # Whether to save raw data locally
  save_clean_locally: False # Whether to save clean data locally
  from_local: True # Use local raw data for download step
  local_fname: '/Applications/python_files/anime_recommendations/data/animelist.csv' # Filename of local raw data

model: # Settings for neural network
  test_size: 10000
  kernel_initializer: 'he_normal'
  TPU_INIT: False
  start_lr: 0.00001
  min_lr: 0.00001
  max_lr: 0.00005
  batch_size: 10000
  rampup_epochs: 5
  sustain_epochs: 0
  exp_decay: 0.8
  embedding_size: 128
  model_loss: 'binary_crossentropy'
  optimizer: 'Adam'
  weights_artifact: 'wandb_main_weights.h5'
  epochs: 20
  activation_function: 'sigmoid'
  checkpoint_metric: 'val_loss'
  save_weights_only: True
  save_best_weights: True
  save_freq: 'epoch'
  save_model: True
  model_name: './wandb_anime_nn.h5' # Path to use if you want to save model to your local machine
  verbose: 1
  model_artifact: 'wandb_anime_nn.h5' # Artifact name for the model
  history_csv: 'wandb_anime_nn_history.csv'
  monitor: 'val_loss'
  mode: 'min'
  anime_weights: 'wandb_anime_weights.csv' # Numpy array of anime weights
  user_weights: 'wandb_user_weights.csv' # Numpy array of user weights
  an_weights_fn: './wandb_anime_weights.csv'
  id_weights_fn: './wandb_user_weights.csv'
  ID_emb_name: 'user_embedding' # Name of user weights layer
  anime_emb_name: 'anime_embedding' # Name of anime weights layer
  merged_name: 'dot_product' # Name of merged layer
  model_metrics: ["mae", "mse"] # Metrics to use for model construction

nn_arts: # Names of main/best neural network artifacts
  main_anime_weights: "wandb_anime_weights.csv:v2" # Anime weights from main neural network model
  main_user_weights: "wandb_user_weights.csv:v2" # User weights from main neural network model
  main_weights_art: "wandb_anime_weights.h5:v8" # All weights from main neural network model
  main_history: "wandb_anime_nn_history.csv:v8" # Hisotry file for main neural network
  main_model: "wandb_anime_nn.h5:v6" # Main neural network artifact name
  model_type: "h5" # Neural network model artifact type
  history_type: "history_csv" # Neural network history artifact type
  weights_type: "h5" # Neural network weights artifact type

similarity: # Arguments for anime-based recommendations in similar_anime.py
  anime_query: "YuuYuu☆Hakusho!" #"SilentMöbius" # Input anime to query. Change random_anime to False in order to use.
  random_anime: False # Whether to choose a random anime to assess rather than the anime input under anime_query
  a_query_number: 10 # Number of similar anime to return
  id_query_number: 10 # Number of similar IDs to return in similar_users.py
  max_ratings: 600 # Limit to this many ratings if random_user is True
  sim_random_user: False # Whether or not to use a random user as the sample
  anime_rec_genres: [None, "SLiceOF life", "va#mpire"] # Genres to include in recommendations, must include 3 total
  an_spec_genres: True # Whether or not to limit returned recommendations to specific genres
  types: ["TV", "Movie"] # Potentially ['TV', 'OVA', 'Movie', 'Special', 'ONA', 'Music'] in similar_anime.py
  spec_types: True # Whether or not to specify types
  a_rec_type: 'csv' #Type of anime recommendations artifacts to local machine
  save_sim_anime: True # Whether to save anime recommendation artifacts to local machine

users: # Arguments for user-based recommendations in user_prefs.py, similar_users.py, and user_recs.py
  favorite_percentile: 80 # Percentile of ratings to consider as favorites (i.e. 80 means the top 20% ratings are favorites)
  cloud_width: 600 # Pixel width of word cloud figures to display. Higher widths increase processing time
  cloud_height: 350 # Pixel height of word cloud figures to display. Higher heights increase processing time
  show_clouds: True # Whether to show clouds when running MLflow
  genre_fn: 'favorite_genres.png' # Artifact filename of genre cloud
  source_fn: 'favorite_source_material.png' # Artifact filename of sources cloud
  prefs_csv: 'user_prefs.csv' # Artifact filename of user_preferences
  save_faves: True # Whether to save clouds and CSV file from user_prefs.py to local machine
  latest_user_prefs: 'user_prefs.csv:latest' # Csv file of latest user preferences
  sim_user_type: 'csv' # Type of wandb artifact the list of similar users csv file was saved as
  sim_user_query: 109160 # A User ID to query if use_local_user is True in similar_users.py
  prefs_local_user: False # boolean of whether to use the user_query found in config file for user_prefs.py
  prefs_user_query: 109160 # Query to user in user_prefs.py
  user_recs_fn: "user_recs.csv" # Artifact name of user recommendations in user_recs.py
  save_user_recs: True # Boolean of whether to save users recommendations in user_recs.py
  user_num_recs: 10 # Number of anime recommendations to return in user_recs.py
  num_faves: 2 # Number of a similar user's favorite anime to return in similar_users.py
  TV_only: True # Whether to include only TV shows in user_recs.py
  sim_users_fn: 'similar_users.csv' # Filename of similar users artifact in similar_users.py
  sim_users_type: 'csv' # Artifact type of similar users df
  sim_users_latest: 'similar_users.csv:latest' # Latest artifact for similar users
  ID_fn: "ID_used.csv" # from similar_users.py, the ID used for MLflow
  flow_user: "ID_used.csv:v0" # latest artifact taken from similar_users.py, ID used for MLflow in user_prefs.py, user_recs.py, and model_recs.py, v0 is 153695
  ID_type: "csv" # Type of artifact the user ID was saved as in similar_users.py
  prefs_from_flow: True # Whether to take the user ID created in mlflow as opposed to a random user or a user specified in config for user_prefs.py
  cloud_type: "png" # Type of genre and source cloud artifacts for user_prefs.py
  fave_art_type: "csv" # Type of data frame containing favorite genres and sources for user_prefs.py
  pref_random_user: False # Whether to use a random user for user_prefs.py
  user_recs_random: False # Whether to use a random user for user_recs.py
  user_recs_query: 109160 # User to query in user_recs.py
  recs_sim_from_flow: True # Whether to get user recommendations from the latest similar users artifact in user_recs.py
  user_recs_type: 'csv' # Artifact type of user-based recommendations csv file in user_recs.py
  recs_ID_from_flow: True # Whether to use the user ID artifact created in MLflow
  recs_n_sim_ID: 10 # Number of similar users to include in user_recs.py
  recs_ID_from_conf: False # Whether to use the user ID specified in config file under user_recs_query
  save_sim_locally: True # Whether to save data frame of similar users to local machine in similar_users.py
  ID_rec_genres: ["Action", "None", None] # Genres to include in recommendations in user_recs.py, must include 3 total
  ID_spec_genres: False #Bool, whether to limit returned recommendations to anime of specified genres
  recs_pref_from_flow: False # Bool, whether to use preferences csv file artifact created in user_prefs.py as input for user_recs.py
  prefs_input_fn: 'user_prefs.csv:latest' # version of Name of csv file artifact created in user_prefs.py to use as input in user_recs.py
  prefs_input_type: 'csv' # Type of version of csv file artifact created in user_prefs.py for use in user_recs.py  

model_recs: # For recommendations based on the ranking model
  model_recs_fn: 'model_recs.csv' # Artifact filename for ranking-based anime recommendations
  save_model_recs: True # Whether to save ranking-based anime recs to local machine
  model_num_recs: 10 # Number of ranking-based anime recs to return
  specify_types: True # Whether to specify the types of anime to return in ranking-based recs
  anime_types: ["TV", "Movie"] # Types of anime to return in ranking-based recs, potentially ['TV', 'OVA', 'Movie', 'Special', 'ONA', 'Music']
  model_genres: ['Action', 'Comedy', None] # Genres to include in ranking-based recs, must include three total
  specify_genres: False # Whether to specify genres in ranking-based recs
  min_score: 0.00 # Minimum rating of anime recs to return
  max_score: 10.00 # Maximum rating of anime recs to return
  model_user_query: 109160 # User query for model recs if a local user is queried
  model_recs_type: 'csv' # Artifact type of model recs
  model_ID_flow: True # Whether to use the same user that was used in MLflow
  model_random_user: False # Whether to use a random user
  model_ID_conf: False # Whether to use the ID specified under model_user_query
