main:
  download_repository: "https://github.com/Dyrutter/anime_recommendations#download"  
  project_name: anime_recommendations
  experiment_name: development
  execute_steps:
    - download
    - preprocess
    - neural_network
    - save_weights 
    - similar_anime
    - similar_users
    - recommendation
    - API
    #- EDA
  random_seed: 42
data:
  stats_url: "https://github.com/Dyrutter/anime_recommendations/blob/main/data/user_stats.parquet?raw=True"
  synopses_url: "https://github.com/Dyrutter/anime_recommendations/blob/main/data/synopses.csv?raw=True"
  all_anime_url: "https://github.com/Dyrutter/anime_recommendations/blob/main/data/all_anime.csv?raw=True"

  stats_artifact: "user_stats.parquet"
  stats_artifact_type: "raw_data"
  stats_artifact_description: "Main statistics file. Contains columns 'user_id', 'anime_id', 'watched_episodes', 'rating', 'watching_status'"
  stats_artifact_latest: "user_stats.parquet:latest"

  synopses_artifact: "synopses.csv"
  synopses_artifact_type: "raw_data"
  synopses_artifact_description: "File containing synopses"
  synopses_artifact_latest: "synopses.csv:latest"

  all_anime_artifact: "all_anime.csv"
  all_anime_type: "raw_data"
  all_anime_description: "File containing descriptive stats for all anime"
  all_anime_artifact_latest: "all_anime.csv:latest"

  preprocessed_stats: "preprocessed_stats.parquet"
  preprocessed_stats_type: "preprocessed_data"
  preprocessed_stats_description: "Preprocessed stats file to be used for model training"
  preprocessed_stats_artifact: "preprocessed_stats.parquet:latest"
  save_raw_locally: False
