name: model_recs
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.0
  - pandas=1.5.3
  - pyarrow=2.0
  - scipy=1.9.2
  - pip=22.3.1
  - scikit-learn=1.2.1
  - IPython=8.8.0
  - pip:
      - wandb==0.15.3
      - setuptools==66.1.1
      - omegaconf==2.2
      - mlflow==2.1.1
      - tensorflow-macos==2.12.0
      - tensorflow-metal==0.8.0