name: download
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.0
  - requests=2.26.0
  - pip=22.3.1
  - hydra-core=1.3.1
  - pandas=1.5.3
  - pip:
      - wandb==0.15.4
      - hydra-joblib-launcher==1.2.0
      - setuptools==66.1.1
      - protobuf==3.19.0
      - omegaconf==2.2
      - mlflow==2.3.0
